### ISSUE TITLE
Sound with repeating keys

### ISSUE THREAD

**Issue by YPetremann** [mattogodoy/hacker-sounds#12]
When pressing a key (space for example) it only trigger a sound when pressing and releasing, not for each space written, maybe putting this behind a setting

**Comment by mattogodoy** [comment]
This is done like that on purpose for performance reasons.
Look at https://github.com/mattogodoy/hacker-sounds/pull/5

**Comment by YPetremann** [comment]
As I've seen in the addons it make sound not repeatable using debounce, why not making the delay an option, so people liking the repetition would put 1 and people wanting it debounced put 100 ?

**Comment by mattogodoy** [comment]
It would be a good idea, yes, but I encourage you to try it locally first to see if reducing the debounce actually does what you expect.
That fix was added because without the debounce the sounds were not very consistent in some computers.

This said, VSCode extensions don't have a very good UI for these kind of settings. If you have an idea on how to add it, please submit a pull request and I will gladly review it 😃

**Comment by YPetremann** [comment]
1) I already tried it with 1 as debounce time
2) I will do a pull request soon
